application:
  connectTimeout: 5000
  readTimeout: 5000

movie-api:
  uri-base: http://www.omdbapi.com/
  api-key: ${API_KEY}

spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/prod?retryWrites=true&w=majority&serverSelectionTimeoutMS=10000&connectTimeoutMS=10000
  security:
    user:
      name: ${AUTH_USERNAME}
      password: ${AUTH_PASSWORD}
