application:
  connectTimeout: 5000
  readTimeout: 5000

movie-api:
  uri-base: http://www.omdbapi.com/
  api-key: ${API_KEY}

spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/prod?retryWrites=true&w=majority&serverSelectionTimeoutMS=90000&connectTimeoutMS=90000
