application:
  connectTimeout: 5000
  readTimeout: 5000

movie-api:
  uri-base: http://localhost:12345/
  api-key: test

spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/test?retryWrites=true&w=majority&serverSelectionTimeoutMS=10000&connectTimeoutMS=10000
  security:
    user:
      name: admin
      password: admin
