application:
  connectTimeout: 5000
  readTimeout: 5000

movie-api:
  uri-base: http://localhost:12345/
  api-key: test

spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/test?retryWrites=true&w=majority&serverSelectionTimeoutMS=90000&connectTimeoutMS=90000
